### ISSUE TITLE
goimports now merges imports by default

### ISSUE THREAD

**Issue by tabboud** [palantir/go-ptimports#67]
## What happened?

As of the following commit, goimports now groups all imports into 1 top level block which breaks the `Refactor` behavior in go-ptimports. 
For example, the following test will now fail once we bump past the below commit on `golang.org/x/tools`
https://github.com/palantir/go-ptimports/blob/3ef1ca02bed680b736fca886de9846a5449e1af3/ptimports/imports_test.go#L96

https://go-review.googlesource.com/c/tools/+/189941
https://github.com/golang/tools/commit/ea4142463bf318ea636acb7d053d0c3ebbe51e47#diff-ed5961d8394837989d257d6588e5bca18ecbb345aca79036171695e5d0e321f8

**Comment by nmiyake** [comment]
From what I can tell, this is due to a behavioral change in `golang.org/x/tools`. Given that this is the behavior we typically want, I think this is fine.

I changed the test case you referenced to match the new behavior and made the bump in #78 .
